### ISSUE TITLE
Vaccination of recovered persons (1/1) is (wrongly) flagged invalid for 14 days after immunization date

### ISSUE THREAD

**Issue by disklammer** [Digitaler-Impfnachweis/covpass-ios#100]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Max
- OS version: iOS 15.2.1
- App version: 1.15

## Describe the bug

Recovered persons are only required to get a single vaccination dose in order to qualify as "fully vaccinated". A **14-days grace period is not required; Vaccination is complete on the day of the vaccination.** Please see bullet 2 on [https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html?nn=169730&cms_pos=3](url) for an exact description.
Certificates issued to this group indicate vaccination "1/1".

"CovPass Check" fails to verify these certificates during a 14-days period after the vaccination date for mRNA vaccines. This is the correct behavior for the "normal" 2-dose vaccination cycle but not for those who recovered before vaccination.
Please update the rule sets to fix this.

Btw: "Cov Pass" correctly states "Valid since \<_Vaccination Date_\>" for these certificates.

## Steps to reproduce the issue

1. Try to verify a (1/1) vaccination certificate of a recovered person on the vaccination date or within 14 days after the vaccination date.
2. Verification fails: "This certificate does not comply with all conditions. More details can be found in "CovPass".
3. (Open CovPass to find "This certificate is valid from \<_Vaccination Date_\>.", i.e. verification is done correctly, there)

## Expected behaviour

Verification is successful.

## Possible Fix

Probably an update of the rule definition will be enough.

## Additional context

This unintended behavior could be observed with Booster (3/3) certificates previously. (Has been fixed according to issue log.)

**Comment by timokoenig** [comment]
The rules have not been updated yet. Related to this ticket https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97

**Comment by disklammer** [comment]
This is not a new rule introduced by the latest (15.01.2022) revision of the Verordnung. It has been in place since ~June 2021. So it's not really related to the latestst one. Can be fixed by a rule update for sure, though.

**Comment by Ein-Tim** [comment]
@timokoenig CWA has a mechanism which detects if a 1/1 vaccination is not from J&J, it is not necessary to show a countdown but the certificate is valid instantly. However, it seems like also CovPassCheck does not validate these certificates correctly?

**Comment by timokoenig** [comment]
ahhh okay this is the J&J case. That's a difficult one.

The 1/1 normal full certificates from J&J can not be distinguished from a booster vaccination. There was nothing we can do up until now. So with the rules prior the 15th these people had to wait 14 days due to the EU schema that was implemented.

Now with the rule change this case is a little different. J&J no requires 2 vaccination as far as I know so we do not run into that issue anymore. These rules have not been implemented yet therefore the link to ticket #97 . I am not sure if those certificates need to be reissued after changes have been implemented. This has to be confirmed by the team

**Comment by disklammer** [comment]
@timokoenig No, this is not J&J. It is a (1/1) dose of Biontech or Moderna. This is an official vaccination scheme for those who recovered before vaccination.
Example:
1. Positive PCR sample on 01.06.2021
2. Vaccination on 03.01.2022

=> Fully vaccinated from 03.01.2022

**Comment by disklammer** [comment]
> @timokoenig CWA has a mechanism which detects if a 1/1 vaccination is not from J&J, it is not necessary to show a countdown but the certificate is valid instantly. However, it seems like also CovPassCheck does not validate these certificates correctly?

Exactly! CWA correctly shows "2G", CovPass shows "Certificate valid". CovPass Check shows "not all conditions satisfied".

**Comment by timokoenig** [comment]
@disklammer thank you for the confirmation.

Can you do the rule check for Germany in your CovPass? This is in the upper left on the Home Screen. Simply click on that, select Germany and the current date. Does the check show you any errors? I am wondering if the rules might have been out of date in the Check App since there is a rule for that exact case

**Comment by disklammer** [comment]
@timokoenig Did you just update the rule set? 🙂
I just did the following:
1. Travel check for Germany in CovPass -> "Certificate not valid. Vaccination date less than 14 days ago."
2. Switched country to Albania -> "Certificate is valid"
3. Switched back to Germany -> "Certificate is valid" 🤯
4. Updated rule set manually in CovPass Check -> "Latest rules from 17.01.2022, 17:48"
5. Checked certificate -> Verified correctly ✅

**Comment by timokoenig** [comment]
@disklammer that would've been funny but no 😄 

Sometimes the rule update mechanism takes some time depending on the delta size. The app itself ships with an initial rule set that might still have the old rules in it. I guess the second time you checked against the updated rule set. I think there need to be some improvement to indicate that the rules are currently updating. FYI @alexcimander 

As far as I know the initial rule set will be updated in the next release so that problem should be mitigated for now

**Comment by disklammer** [comment]
@timokoenig Ok I just realized it simply shows the timestamp of the last list/rule update in the CovPass Check app. I misinterpreted this as a "revision timestamp". So to summarize: It works fine. Closing.
