### ISSUE TITLE
Optimise App for usage on iPads

### ISSUE THREAD

**Issue by BarbarossaCode** [Digitaler-Impfnachweis/covpass-ios#11]
Many shops are using iPads as cash registers. So it would be nice fully support iPads.

**Comment by visualication** [comment]
The apps are running on iPads in iPhone Mode.

**Comment by jleufgen** [comment]
The CovPass App can already be used on a tablet. Therefore, a new App in tablet format is not needed.

**Comment by yannikbloscheck** [comment]
As the interface isn't adjusted for iPad's it isn't really usable there in a comfortable way.
It really shouldn't be good enough for such an app to just work in some way, because the platform vendor (Apple) allows it to be displayed in compatibility mode to enable the features for users when the developer is bad or very lazy. Instead it should be a good platform citizen.
In theory the app could use the Comic Sans font at 3pt. That also would theoretically work in some way, but it also wouldn't be good enough. That's why isn't wasn't done this way. Similar it's just not sufficient to allow the app to be displayed only in compatibility mode on iPad instead of having a flexible interface for it.
I can understand that it might not have been a top priority in the initial rush to get the app ready, but there has been enough time to improve it by now.
