### ISSUE TITLE
Onboarding reappears after update to version 1.3

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#15]
The onboarding just reappears after the update to version 1.3. Since I haven't registered any certificates, I can't say whether the the app has been completely resetted (all data lost) or just the onboarding came up again.
Anyways, after an update, there should maybe be a splash screen telling the user what's new, but not the onboarding which shows when the user installs the app.

**Comment by timokoenig** [comment]
This was an intended behavior for that version since we don't have a "New In This Version" screen yet and the onboarding slightly changed. In version 1.3 we added other various features like test and recovery certificates therefore the data privacy changed and it needed to be displayed to the user again.

I agree that a dedicated screen would be better suited for this

Important note: **No data is lost in this process!**

**Comment by Ein-Tim** [comment]
@timokoenig 

Okay, thanks for the information. I'll open a new dedicated enhancement request for this later on.  

Are you sure that every time the privacy note changes the user has to see it again? 
The CWA doesn't show it every time it changes...

Anyways, closing as answered.

**Comment by timokoenig** [comment]
@Ein-Tim it depends on how significant the changes are and how to comply with GDPR guidelines. In most cases a passive notice is fine and in other cases you would have to explicitly list all changes made to the user if those are a lot different from what he has previously agreed on. It's always hard to find the right balance between legal compliance and user experience
