### ISSUE TITLE
Release 1.19.1?

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#162]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question
Version 1.19.1 was just released on the App Store, please release the source code here and create a GitHub release.

**Comment by alexcimander** [comment]
Hi @Ein-Tim, 

due to an bug within the CovPassCheck valid recovery certificates (and only valid recovery certificates) where displayed as "valid since 0 months". This lead to an hotfix release that was started yesterday and could be released this morning. 
Code will be released asap. 

Thank you for your patience :-)

**Comment by Kurt57** [comment]
Hi @Ein-Tim the code will come immediately. I have to solve some git issues. Related to @timokoenig ´ s #157 issue. After that we will publish the code to main branch. Hopefully it´s fine for you all. But the release branch 1.19 already up to date.
