### ISSUE TITLE
Full vaccination date 

### ISSUE THREAD

**Issue by tomml** [Digitaler-Impfnachweis/covpass-ios#17]
The full vaccination date could be faked easily by editing the iOS global date setting.
A better approach is to use the actual vaccination date instead of the OS system date.

**Comment by Ein-Tim** [comment]
It's not a problem if the user changes his/her date in the iOS settings, since the QR-Code has to be scannend with the CovPassCheck App and it will still show that the QR-Code is invalid, since the date of the vaccination is included in the payload of the QR-Code. So as long as the person with the CovPass Check app has set the date of his/her phone right, this is not a problem. 
Related discussion: https://github.com/corona-warn-app/cwa-documentation/issues/642

**Comment by jleufgen** [comment]
Hi all, in one of the next releases the problem will be covered. Best regards!
