### ISSUE TITLE
CovPass shows "Grundimmunisierung vor xx" even though there is one 2/2 vaccination & one recovery certificate in the app 

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#187]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 15.5
- App version: 1.25

## Describe the bug

The CovPass-App shows "Grundimmunisierung vor 8 Monaten" (in my case) although I have the following certificates in the app:
- 2/2 vaccination certificate
- certificate of recovery

## Steps to reproduce the issue

1. Add a 2/2 vaccination certificate to the app
2. Add a certificate of recovery to the app
3. See that the app still shows that one is only "Grundimmunisiert" although CovPassCheck says this combination of certificates as valid for 2G+.

## Expected behaviour

Either "Auffrischimpfung vor..." (not really appropriate as there was no booster vaccination. Or "Vollständig geimpft" and not only "Grundimmunisiert".

## Possible Fix

Change the wording & the logic. 

## Additional context

Screenshots:

<img src="https://user-images.githubusercontent.com/67682506/170084968-a45a7476-a233-440b-9c3a-8b06752e19c4.jpeg" width="300">
<img src="https://user-images.githubusercontent.com/67682506/170084993-bce8ecc0-f30a-413c-af21-69bf2d4e1c16.jpeg" width="300">

**Comment by alexcimander** [comment]
Good Morning Tim,

the wording only reflects the status of the DCC on the startpage - it does not represent a combined status of all your stored DCCs. Your 2/2 for now still reflects your basic immunization, even though you will need even more "proofs" for 2G+. 

We are aware that one DCC on startscreen level isn't always enough to enter a venue. This is why the upcoming release will be a new "modal view" - our take on the certificate switcher which allows you to switch fast and easy between your most important DCCs. 

This will allow you to have all the proofs you need to enter venues - even if the rules are or will be different for all federal states or even counties within germany.

 Thank you for your support! 👍

**Comment by Ein-Tim** [comment]
Hey @alexcimander,

thanks for your answer! I guess this certificate switcher will also improve the wording, as one certificate will then say "Impfung" & the other one "Genesung".

**Comment by alexcimander** [comment]
Hey @Ein-Tim ,

based on the DCC-Type you will find:

Vaccination:
1/2, 1/1: "Vaccination 1 out of 2" / "Vaccination 1 out of 1"*
2/2, 2/1 (if 1/1 JJ): "Basic Immunization"*
2/1 (if no 1/1 JJ), 3/3 etc.: "Booster Vaccination"*
2/1 (if 1/1 JJ and Recovery (oldest DCC)): "Booster Vaccination"*

*Due to the new regulations for JJ vaccinations we adapted the value for Vaccinations based on a 1/1 JJ. This was not adapted in the business rules (and therefore CovPassCheck) since the rule do not allow to check within context. However we are working on feasable solutions to adapt business rule checks for all member states.

Recovery:
Recovery: "Recovery"

Test:
PCR: "PCR test"
Rapid Antigen: "antigen rapid test"

**Comment by Ein-Tim** [comment]
Hey @alexcimander, 

thank you very much for the explanation! This sounds like a good solution, but I have to look at it myself (:

Thanks!

**Comment by Ein-Tim** [comment]
This has been improved with version 1.26. I consider this as fixed. Closing.
