### ISSUE TITLE
Integrate CCL

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#188]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
CovPass does not use CCL to determinate status of certificates.

## Suggested Enhancement
Use the Common Covid Logic the CWA-Team has provided to determine a certificates status and reissue certificates. 

## Expected Benefits
Consistent status of certificates in both apps, CWA & CovPass. This also saves the CovPass-Team a lot of work, as ones implemented, the rules are maintained by the CWA team.

**Comment by Ein-Tim** [comment]
Will someone at least give me some feedback on this issue, e.g. that you've seen it? (-:

**Comment by alexcimander** [comment]
Hey @Ein-Tim,

seen it! Sorry for the late reply. 

We are currently preparing ourselves for potential new Covid-waves that might come with new regulations, admission concepts, rules etc. Saying that we are currently investigating on feasable solutions that are "easier" to adapt to frequently changing requirements. CCL is one of the frameworks which is part of the discussion since it is a charming solution for that. We will let you know how these discussions proceed! 😊

**Comment by Ein-Tim** [comment]
Thanks!

**Comment by Ein-Tim** [comment]
Hey @alexcimander, was there a decision made whether to integrate with CCL or not? To be honest, I don't really see any points which speak **against** using CCL, as this safes a lot of work for your team, or am I mistaken?

**Comment by Ein-Tim** [comment]
If I understand the note 
> 
To determine the vaccination status, we are now using the TSI Rules that we also implemented on the CovPassCheck app.

in https://github.com/Digitaler-Impfnachweis/covpass-ios/releases/tag/v1.38.0 correctly, this has been implemented?

**Comment by Kurt57** [comment]
> If I understand the note
> 
> > To determine the vaccination status, we are now using the TSI Rules that we also implemented on the CovPassCheck app.
> 
> in https://github.com/Digitaler-Impfnachweis/covpass-ios/releases/tag/v1.38.0 correctly, this has been implemented?

Yes. it is implemented already in 1.37

**Comment by Ein-Tim** [comment]
Closed as implemented.
