### ISSUE TITLE
CovPass Check: Vaccination certificate invalid

### ISSUE THREAD

**Issue by seboettg** [Digitaler-Impfnachweis/covpass-ios#34]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- OS version: 14.6
- App version: 1.4.1 (1)

## Describe the bug

I'm not sure if it's a bug in the app or more of a problem with the certificate. I got my long awaited second vaccination yesterday at my vaccination center. I got also the "EU DIGITAL COVID VACCINATION CERTIFICATE" which I also added directly in the Corona Warn app. Today I tried to check the validity of the certificate. To do this, I downloaded the CovPass Check App and scanned the QR code. Contrary to my expectations, an error message appears: 

> **Zertifikat ungültig**
> Das geprüfte Zertifikat ist aus einem der folgenden Gründe ungültig:
> * Das Zertifikat entspricht nicht den in Deutschland geltenden Regelungen für EU Digitale COVID-Zertifikate.
> * Die Signatur ist nicht gültig oder der QR-Code ist nicht lesbar

Afterwards I scanned the QR code of the certificate with the CovPass app to ensure the reason is no issue with the Corona Warn App. The scan of the QR code worked without any problems. However, the check with the CovPass Check App leads to the same result: "Zertifikat ungültig".

## Steps to reproduce the issue

I have no idea how to reproduce this behaviour

## Expected behaviour

The correct and meaningful message appears.

## Additional context

Of course, my full vaccination protection is only achieved in 14 days. But this does not mean that the certificate is invalid. If this is the reason for this behaviour, the CovPass Check App should show a clear message: "the full vaccination protection is only achieved in X days" or similar.

Maybe this is just a bug of the software for the certificate issuer. Or there is more fundamental problem with the certificates or signature verfication.

**Comment by Ein-Tim** [comment]
@seboettg 

Yes the reason for this behavior is that since the vaccination 14 days haven't passed yet.

**Comment by Ein-Tim** [comment]
There is an enhancement request open for this here: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/21

**Comment by seboettg** [comment]
Thanks, for the quick answer. Please add clear and meaningful error messages, to avoid confused users ;-)

**Comment by timokoenig** [comment]
It's always hard to find the right balance between what we would like to show and data privacy. Better and meaningful error messages also mean that we expose more information to the user that checks your certificate. In most cases even name and birthdate is too much but that's the minimum we need to identify the person showing the certificate. I know the struggle and we are trying to find the right solution for it

**Comment by My1** [comment]
well the qr code contains the data and I wouldnt be surprised if people who really want the data just scan it with something else.

just hiding the data from the app screen wont magically erase the data.

being able to tell the user that they need a second shot or that they need to wait before full immunization or whateveris pretty useful as an app just saying it does not conform to some arbitrary requirements that arent even listed "or technical error" would likely not satisfy users.

or this fun thing:
https://www.heise.de/news/Apotheken-Wie-Sicherheitsforscher-das-Impfzertifikats-Portal-kompromittierten-6145902.html

which might need a mass revocation to the the drugstores (or their infrastructure) apparently using a single key amongst themselves


if certs are revoked the one with the covpass check app could just tell the user that they need a new certificate as the old one was axed.

being able to give users clear reasons on why they are rejected or have to do certain things will likely be key when needing a lockdown that excludes vaccinated people

**Comment by timokoenig** [comment]
If information like this needs to be shown to the user then in the Pass App directly to the person owning the certificate and not to the person checking the certificate. The person with the CheckApp should get as little information about the other person as possible

**Comment by My1** [comment]
> If information like this needs to be shown to the user then in the Pass App directly to the person owning the certificate and not to the person checking the certificate. The person with the CheckApp should get as little information about the other person as possible

I wouldnt expect everyone to have the app much less an up to date one. for example in my family someone has a smartphone but their plan has no internet and wifi is busted, so they'll need the apk which obviously cannot really update iself or even pull the regulation and then there are people who dont even have or want a smartphone and will just use the paper cert.

also not showing the data in the covpass check doesnt magically erase the data as said.

if data shouldnt be available to a party it shouldnt even be in the qr, it might as well have only an identifier and the app checks the status online but obviously that isnt done due to privacy issues and all.

**Comment by timokoenig** [comment]
Sadly there are always limitations to the way we do it because of data privacy regulations we have with this app. If the paper cert is invalid or some other error occurs I rather suggest giving it to someone in your close circle that can check it for you with CovPass. I believe we can improve the error messages in CovPassCheck so that everyone gets just enough information.

Of course it doesn't erase the data but that's why we don't save it in CovPassCheck in the first place. You should be cautious when someone else is scanning your certificate with a different app or scanner since you don't know how they handle your personal information.

**Comment by seboettg** [comment]
Even from a data privacy perspective, I don't see a problem if the Check App shows that the full vaccination protection is not achieved yet, but will be in X days...

**Comment by My1** [comment]
> Of course it doesn't erase the data but that's why we don't save it in CovPassCheck in the first place. You should be cautious when someone else is scanning your certificate with a different app or scanner since you don't know how they handle your personal information.

sure I am not saying the covpasscheck app stored anything (except obviously up to date regulation and trust info for offline running, in fact it even blocks screenshots, meaning you cant even easily get out the data from the covpass check directly.

also not even sure if people would show you that they actually scan using covpass check actively, especially if they did wanna scan with another app. hell rather than covpass check they could scan with covpass for user edition and get all the data.

**Comment by jleufgen** [comment]
Hi all :) This topic will be worked on in one of the next sprints. Thank you for the feedback! Best regards!
