### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#35]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
The app does not support dark mode.

## Suggested Enhancement
Add support for dark mode (https://developer.apple.com/documentation/uikit/appearance_customization/supporting_dark_mode_in_your_interface).

## Expected Benefits
Nicer UX (;

**Comment by jleufgen** [comment]
Hello, thank you for your feedback! Dark mode support is currently under discussion.

**Comment by jleufgen** [comment]
The Dark Mode setting is not supported at this time, as it is not conducive to the accessible implementation of the app.

**Comment by haukesomm** [comment]
@jleufgen can you please elaborate on this? I would argue that a dark mode improves accessibility in various ways, ranging from reduced eye-strain in dark environments to improved overall contrast. It is also an extremely popular option amongst many users and even recommended in Apple’s design guidelines.

Also, the feature can easily be implemented by changing only a few lines of code since SwiftUI provides an almost complete implementation out of the box. The only assets that would need to be adjusted are some images that currently use a static white background. 

I would be happy to open a pull request for this feature and contribute the implementation on my own.
