### ISSUE TITLE
Do not show information about vaccination certificate and just show QR Code

### ISSUE THREAD

**Issue by benzman81** [Digitaler-Impfnachweis/covpass-ios#62]
## Avoid duplicates
* [x ] This enhancement request has not already been raised before

## Current Implementation
The app shows information about vaccination state, person name and birth date, and number of shots etc. 
Also a hint is shown to not show this data at events, restaurants etc.

## Suggested Enhancement
Do not show the information anymore to force validation via QR code (CovPass Check or similar).

## Expected Benefits
Currently, literally just a few to almost no one checks the QR code when validating the vaccination state. Even the passport is not always checked. The always want you to show the information in the app, besides the hint ther not to show it.

Real world is like the following:
„Please show me your vaccination state“
„Ok, here“ (opening the app presenting the QR code)
„Could you you click on the code for the details?“
„OK“ (clicking to go to details)
„Could you please scroll down a bit so that I see the number of shots“ (even that happens seldom)
„Here we go“ (scrolling down)
„Please come in“.

This or similar happens to me and others all the time. So I actually dont even need to be vaccinated and can just use a screenshot from someone else. Going further I could change name and birthdate using a photo editing software and all will be fine since no one validates the QR code.

That is why I wouldnt show any information about the vaccination state to force everyone to scan and validate the code. I dont get why everyone hypes the fact, that there are fake QR codes around since it is much simple to enter a 2G or 3G event just by using an edited screenshot 🤷🏼‍♂️

**Comment by benzman81** [comment]
Just watched episode 8 (10.11.2021) from german tv show „Zervakis & Opdenhövel Live“. The checked how the certificates are checked by restaurants. Every restaurant that checked the certificate just let the user show the app an no one checked their ID either. The TV show called it „ideal“ (ger. „vorbildlich“), so even they dont know how to check correctly.
Right after the test they showed how easy it is to get a fake vaccination certificate from telegram, but this is not even needed when it is not correctly checked.
Why is this not communicated more? 3G or 2G does not make any sense this way 🤷🏼‍♂️ Sorry for being a bit emotional…

**Comment by alexcimander** [comment]
Hey benzman81, 

thank you for your honest feedback and we feel you! We are aware that the usage of the CovPassCheck is lagging behind and we do our best to improve the situation.

So when it comes to the technical part the CovPass already includes a "QR-Code-only" screen. You can find it in the detail view of your certificate. Using that the app will just show the QR-Code without any further details.

Adding the hints you pointed out was another step to make everyone clear that there is an app that can and should be used.

However, we are still working on more ways to improve the situation from a technical point of view.

At last the communication is key! Personally, I have the Check-App always ready to show the staff how it works. 

There are some key advantages if you use the CovPassCheck:
1.) You get the result without doing the math
2.) You see the date of birth etc. in a perfectly readable format.
3.) You don't have to touch everyones phone
4.) You can be safe that everyone in your restaurant/bar etc. is really vaccinated or tested (of course with the additional ID check)
[..]

Most of the times this is really "eye-opening" since a lot of people aren't really aware of all the risks.
So we are always happy for fellow companions that spread the message 🙏 

But you are right. More communication is needed and we are working on it.

Thank you once more for the feedback! 

Alex

**Comment by benzman81** [comment]
@alexcimander 

Thanks for your statement. 

Some thoughts:
1. You could remove the checkmark and the "fully vaccinated since xxx" from the main screen
2. Clicking on the QR Code or the "show certivate" link shows a popup first with the hint to not show the following details in restaurants etc. and that you should use the covpass check app. Then you can continue or cancel.

This way, it is more clear to both, user and controlling instance. You can show them the popup without revealing information. This gives you a valid argument when the controlling instance wants you to show the details and also explaings them how to validate it.

**Comment by benzman81** [comment]
Oh, one more addition to my thoughts. The popup could also contain a qr code with the URL to the covpas check app, so that the controlling instance could scan it with their camera and download it right away.

**Comment by alexcimander** [comment]
Hey @benzman81,

we got some news! We are currently working on several features that will further prevent the misuse of the CovPass-App as the "Check-App". In total app will have less details on the front page that will make it harder to see if a full immunization is actually present without the Check-App along with some more preventive actions. 

These features will arrive with the upcoming releases -  so please stay tuned for more details.

Thank you again for participating 👍 🥳

**Comment by Kurt57** [comment]
hi @benzman81 is this solved and we can close this?

**Comment by benzman81** [comment]
Jepp, looks good 👍
